#!/usr/bin/env node
const fs = require('fs');
const { Client } = require('pg');

// Tables in order to satisfy foreign keys
const TABLES = [
  'usuarios',
  'productos',
  'metodos_pago',
  'facturas',
  'factura_detalles',
  'sesiones'
];

function sqlEscape(val) {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
  if (typeof val === 'number') return String(val);
  // For objects (JSON), stringify
  if (typeof val === 'object') val = JSON.stringify(val);
  // Escape single quotes
  return "'" + String(val).replace(/'/g, "''") + "'";
}

async function exportTable(client, table, out) {
  const res = await client.query(`SELECT * FROM ${table}`);
  if (res.rows.length === 0) return;
  const cols = res.fields.map(f => f.name);
  out.push(`-- Data: ${table}`);
  for (const row of res.rows) {
    const vals = cols.map(c => sqlEscape(row[c]));
    out.push(`INSERT INTO ${table} (${cols.join(',')}) VALUES (${vals.join(',')});`);
  }
  out.push('');
}

async function main() {
  const args = process.argv.slice(2);
  const outFile = args[0] || './backup_data.sql';
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    console.error('Set DATABASE_URL environment variable first.');
    process.exit(1);
  }

  const client = new Client({ connectionString });
  try {
    await client.connect();
    const out = [];
    out.push('-- Export generated by scripts/export-data.cjs');
    out.push('BEGIN;');
    out.push('SET CONSTRAINTS ALL DEFERRED;');
    for (const t of TABLES) {
      try {
        await exportTable(client, t, out);
      } catch (err) {
        console.warn('Skipping table', t, 'error:', err.message || err);
      }
    }
    out.push('COMMIT;');
    fs.writeFileSync(outFile, out.join('\n'));
    console.log('Wrote', outFile);
  } finally {
    await client.end();
  }
}

main().catch(err => { console.error(err); process.exit(1); });
